pkg/cli/admin/upgrade/recommend: Enable precheck and accept gates
To make that functionality generally available.  This could be a more
thorough overhaul, e.g. I could drop the precheckEnabled knob
entirely.  But I'm doing the smallest possible pivot now, in case
folks want to backport to older 4.y.  And I can do the dev-branch
polishing later on.

The:

  error: issues that apply to this cluster but which were not included in --accept: AlertNoTestData,ConditionalUpdateRisk

output that b74a129723 (pkg/cli/admin/upgrade/recommend: Don't error
on unaccepted issues when the feature gate is off, 2025-08-02, #2069)
had removed from the test fixtures is back, now that the accept gate
is enabled by default (and thus newly enabled for the test suite).