pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring: New test-case
Based on a 'launch 4.16.27 gcp' Cluster Bot cluster, where I cordoned
the compute Nodes and removed a Prometheus Pod:

  $ oc adm cordon -l node-role.kubernetes.io/worker=
  $ oc -n openshift-monitoring delete pod prometheus-k8s-0

I then waited for the monitoring operator to decide it was time to
report the degradation via its ClusterOperator, the cluster-version
operator to pass that along in ClusterVersion, and a bunch of
additional time for 'pending' alerts to cook through to 'firing'.

I could not collect the cluster state with inspect-alerts, because the
Cluster Bot cluster's root credentials do not use a token:

  $ OC_ENABLE_CMD_INSPECT_ALERTS=true oc adm inspect-alerts
  error: failed to get alerts from Thanos: no token is currently in use for this session

So instead, I followed [1] with:

  $ TOKEN="$(oc -n openshift-cluster-version create token default)"
  $ HOST="$(oc -n openshift-monitoring get route thanos-querier -o jsonpath='{.status.ingress[].host}')"
  $ curl -G -k -H "Authorization: Bearer $TOKEN" "https://$HOST/api/v1/alerts" | jq . >pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring-alerts.json

I collected ClusterVersion the usual way:

  $ oc get -o yaml clusterversion version >pkg/cli/admin/upgrade/recommend/examples/4.16.27-degraded-monitoring-cv.yaml

And then generated the output fixtures:

  $ UPDATE=yes go test -v ./pkg/cli/admin/upgrade/recommend/...

[1]: https://docs.openshift.com/container-platform/4.17/observability/monitoring/accessing-third-party-monitoring-apis.html#accessing-metrics-from-outside-cluster_accessing-monitoring-apis-by-using-the-cli