pkg/cli/admin/upgrade: Teach --to about history lookup
Copying from [1], and adjusting to return a pointer instead of a
(non-pointer,found) tuple.  Future work can shift this function into
library-go.  This avoids:

  $ oc adm upgrade --to 4.6.0-fc.5
  error: Can't look up image for version 4.6.0-fc.5. The update channel has not been configured.

When that lookup would succeed when investigating ClusterVersion
status.history:

  $ oc patch clusterversion version --type json -p '[{"op": "add", "path": "/spec/desiredUpdate", "value": {"version": "4.6.0-fc.5"}}]'
  $ oc adm upgrade
  info: An upgrade is in progress. Working towards 4.6.0-fc.5: downloading update

  warning: Cannot display available updates:
    Reason: NoChannel
    Message: The update channel has not been configured.

[1]: https://github.com/openshift/cluster-version-operator/blob/6d56c655ea16f6faee4b65ffef43dcd912657bc6/pkg/cvo/updatepayload.go#L305-L325