pkg/cli/admin/release/mirror: Don't print instructions for 'oc adm release new --mirror ...'
To avoid dying with:

  error: Error creating mirror usage instructions: Unable to parse image reference '': repository name must have at least one component

when either the source was actually an image-stream, which happens
with:

  $ oc adm release new --mirror ...

Without the new Mirror option, the 'new --mirror' case would produce
output like:

  $ oc adm release new --from-release registry.svc.ci.openshift.org/ocp/release:4.2.0-0.ci-2019-09-18-191920 --to-image registry.svc.ci.openshift.org/wking/openshift4:4.2.0-0.nightly-2019-09-18-191920 --mirror registry.svc.ci.openshift.org/wking/openshift4
  ...
  To use the new mirrored repository for upgrades, use the following to create an ImageContentSourcePolicy:

  apiVersion: operator.openshift.io/v1alpha1
  kind: ImageContentSourcePolicy
  metadata:
    name: example
  spec:
    repositoryDigestMirrors:
    - mirrors:
      - registry.svc.ci.openshift.org/wking/openshift4
      source: registry.svc.ci.openshift.org/ocp/4.2-2019-09-18-191920
  ...

due to the non-empty registries map.