pkg/cli/admin/upgrade/recommend: Don't error on unaccepted issues when the feature gate is off
When OC_ENABLE_CMD_UPGRADE_RECOMMEND_ACCEPT is not set to true, the
--accept option does not exist.  In that case, we don't want to error
with [1]:

  error: issues that apply to this cluster but which were not included in --accept: ConditionalUpdateRisk

Instead, we just want to exit happily, because we've already mentioned
the issue earlier in the message.

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29831/pull-ci-openshift-origin-main-e2e-aws-ovn-serial-1of2/1951653929842380800