remove-role-from-user outputs error when target was not found
When `oc adm policy remove-role-from-user` tries to remove non
existing user/sa, the command does not output any error, so users
cannot notice their misoperations like typo.

```
$ oc adm policy remove-role-from-user view non-existing-user
role "view" removed: "non-existing-user"
```

This patch changes to output when `oc adm policy
remove-role-from-user` tried to remove non existing user/sa.

```
$ ./oc adm policy remove-role-from-user view non-existing-user
error: unable to find target [non-existing-user]
```