vendor: Update openshift/api to pick up v4.17 and v4.18 capability sets
Catching up with [1].  Generated with:

  $ go get github.com/openshift/api@master
  $ go mod tidy
  $ go mod vendor
  $ git add -A go.* vendor

all using:

  $ go version
  go version go1.22.2 linux/amd64

This addresses [2]:

  $ cat v4.17-basecap.yaml
  ---
  apiVersion: v1
  platform:
    gcp:
      foo: bar
  capabilities:
    baselineCapabilitySet: v4.17
  $ ./oc adm release extract --install-config v4.17-basecap.yaml --included --credentials-requests --from quay.io/openshift-release-dev/ocp-release:4.17.0-rc.1-x86_64 --to /tmp/test
  error: unrecognized baselineCapabilitySet "v4.17"

because pkg/cli/admin/release/extract_tools.go uses the vendored
openshift/api/config/v1 to unpack capabilities.

[1]: https://github.com/openshift/api/pull/2022
[2]: https://issues.redhat.com/browse/OCPBUGS-41111