minor fix in "oc get --help" text re. "list of common resources"
because:

    $ oc get --help
    Display one or many resources

    Possible resources include builds, buildConfigs, services, pods, etc. To see a list of common resources, use 'oc get'.

but:

    $ oc get
    You must specify the type of resource to get. Use "oc api-resources" for a complete list of supported resources.

    error: Required resource not specified.
    Use "oc explain <resource>" for a detailed description of that resource (e.g. oc explain pods).
    See 'oc get -h' for help and examples.

This brings it in line with kubectl:

    $ kubectl get --help
    Display one or many resources
    (...)
    Use "kubectl api-resources" for a complete list of supported resources.