extract: Make destination paths to absolute to avoid symlink errors
The layer extraction functionality requires absolute paths for creating
symlinks. The input normalization process should turn target paths into
absolute paths. Note that if you are extracting an absolute symlink, we
do not remap it (etc/mtab -> /proc/self/mount, when extracted to /tmp/a,
would be /tmp/a/etc/mtab -> /proc/self/mount).

Bug was `oc image extract IMAGE` (which defaults to `--path /:.`) resulting
in an error:

```
error: unable to extract layer sha256:4f88af2d484bc1dc514fb5fb80259c3b8989127ca8c75fc58b4b85e98550835d from quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f3ba975408deb1df7b4c0b8a3617e339d91e45c08ace87fe529707692df25a9a: invalid symlink "etc/mtab" -> "/proc/self/mounts"
```