`debug` should use watch.UntilWithSync for maximum safety
Some jobs were failing because oc debug took too long and were
seeing:

    Removing debug pod ...
    Starting pod/ip-10-0-131-99us-west-2computeinternal-debug ...
    To use host binaries, run `chroot /host`

    Removing debug pod ...
    error: watch closed before UntilWithoutRetry timeout